# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('meal_plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal1', models.IntegerField()),
                ('meal2', models.IntegerField()),
                ('meal3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ing_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('instruct_id', models.IntegerField(primary_key=True, serialize=False)),
                ('step_num', models.IntegerField()),
                ('instruction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='dashboard.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='dashboard.Tag'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Recipe'),
        ),
    ]
