# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('meal_plan_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ing_id', models.AutoField(primary_key=True, serialize=False)),
                ('ing_name', models.CharField(max_length=60)),
                ('ing_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('instruct_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_num', models.IntegerField()),
                ('instruction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_Goal', models.IntegerField(blank=True, null=True)),
                ('fat_Goal', models.IntegerField(blank=True, null=True)),
                ('carb_Goal', models.IntegerField(blank=True, null=True)),
                ('protein_Goal', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='dashboard.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='dashboard.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='dashboard.Tag'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.Tag'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Recipe'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='meal1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='dashboard.Recipe'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='meal2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='dashboard.Recipe'),
        ),
        migrations.AddField(
            model_name='dailymealplan',
            name='meal3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal3', to='dashboard.Recipe'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='meal_plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DailyMealPlan'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together=set([('meal_plans', 'date')]),
        ),
    ]
