# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealplan',
            name='meal1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='dashboard.Recipe'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='meal2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='dashboard.Recipe'),
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='meal3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal3', to='dashboard.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ing_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=30),
        ),
    ]
