# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20171129_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalorieGoal', models.IntegerField()),
                ('fatGoal', models.IntegerField()),
                ('carbGoal', models.IntegerField()),
                ('proteinGoal', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ing_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailymealplan',
            name='meal_plan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruct_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='preferences',
            name='ingredients',
            field=models.ManyToManyField(to='dashboard.Ingredient'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tags',
            field=models.ManyToManyField(to='dashboard.Tag'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
