# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171201_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
