# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20171201_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_Goal', models.IntegerField(blank=True)),
                ('fat_Goal', models.IntegerField(blank=True)),
                ('carb_Goal', models.IntegerField(blank=True)),
                ('protein_Goal', models.IntegerField(blank=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='dashboard.Ingredient')),
                ('tags', models.ManyToManyField(blank=True, to='dashboard.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
