# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_instruction_step_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='step_num',
        ),
    ]
