# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='calorie_Goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='carb_Goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='fat_Goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='protein_Goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
