# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171206_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymealplan',
            name='date',
            field=models.DateField(),
        ),
    ]
